---
#The following host works on very old version of nginx(1.6.2)
- hosts: banana
  tasks:
  - name: Generate Diffie-Hellman parameters with the default size (4096 bits)
    openssl_dhparam:
      path: /etc/ssl/dhparams.pem
      size: 2048
      state: present
  roles:
    - role: nginxinc.nginx
  vars:
    nginx_install_from: os_repository
    domain: akumasan.tk
    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: "{{ domain }}.conf"
        conf_file_location: /etc/nginx/conf.d/
        servers:
          # Redirect all HTTP traffic to HTTPS
          server1:
            listen:
              listen_localhost:
                # ip: 0.0.0.0
                port: 80
            server_name: "{{ domain }} www.{{ domain }}"
            https_redirect: "$host"
          # SSL configuration
          server2:
            listen:
              listen_localhost:
                port: 443
            server_name: "{{ domain }} www.{{ domain }}"
            ssl: 
              cert: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
              key: "/etc/letsencrypt/live/{{ domain }}/privkey.pem"
              # RFC-7919 recommended: https://wiki.mozilla.org/Security/Server_Side_TLS#ffdhe4096
              dhparam: /etc/ssl/dhparams.pem
              #ecdh_curve: secp521r1:secp384r1
              
              # Enable server-side protection against BEAST attacks
              protocols: TLSv1.2
              ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384"
              prefer_server_ciphers: true
              # Improve HTTPS performance with session resumption
              session_cache: none
              session_timeout: 5m
              stapling: true
              stapling_verify: true

            add_headers:
              strict_transport_security:
                name: Strict-Transport-Security
                value: max-age=31536000; includeSubDomains
              x_frame_options:
                name: X-Frame-Options
                value: DENY always
              x_content_type:
                name: X-Content-Type-Options
                value: nosniff always
              x_xss_protection:
                name: X-Xss-Protection
                value: 1; mode=block always
